# Generated by Django 6.0.1 on 2026-02-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDescription',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='previousjob',
            old_name='company_description',
            new_name='company',
        ),
    ]
